### ISSUE TITLE
Signature Mismatch on v1.0.6

### ISSUE THREAD

**Issue by duckbrain** [blevesearch/vellum#8]
Keep getting signature mismatch problems between my Athens caching module proxy and https://proxy.golang.org/ was the current release by chance retagged?

**Comment by abhinavdangeti** [comment]
>was the current release by chance retagged?

@duckbrain Didn't think so. Are you using blevesearch/vellum directly or indirectly via blevesearch/bleve ?

**Comment by duckbrain** [comment]
I'm using it indirectly via blevesearch/bleve. It's probably my proxy. When I go with `GOPROXY=''` I get

```
github.com/blevesearch/vellum v1.0.6 h1:F7mKWx+xt7e+i3LGtCUhLI2rLonBgT1uke7WP3mL5v4=
github.com/blevesearch/vellum v1.0.6/go.mod h1:vMf1MTDsr8l1N5GEi6idH9zF0w8XuY8W8gFuwkIB77g=
```

Which I assume is the correct one.

When I go through my proxy, it complains about the go.sum. The proxy logs are also complaining about the upstream sum.

```
verifying github.com/blevesearch/vellum@v1.0.6/go.mod: checksum mismatch
        downloaded: h1:doBZpmRhwTsASB4QdUZANlJvqVAUdUyX0ZK7QJCTeBE=
        go.sum:     h1:vMf1MTDsr8l1N5GEi6idH9zF0w8XuY8W8gFuwkIB77g=
```

I'll have to look into clearing a corrupt signature from the proxy. Thanks.

**Comment by abhinavdangeti** [comment]
It's possible I may have messed up in setting up this tag. Let me set up a new tag/release here and for bleve.

**Comment by abhinavdangeti** [comment]
You shouldn't see this issue with blevesearch/bleve@v2.2.1.
